### PR TITLE
Basic mouse picking

### PR DESCRIPTION
**Pull request by Licini**
1. basic mouse selection function to pick objects on screen which will highlight the object as well as its tag in Tree view. (through drawing a instance map for each frame with pixel hex values as keys of a dict of meshes)

2. Multi selection by pressing `shift` to add items and `cmd` to deselect items

3. Objects in selection are stored in a set at `view.selected` and updated constantly

4. highlighting is now accomplished through assigning temporary default color(now yellow) when making buffer without ever modifying objects original color.

5. added mouse state at `mouse.buttons` to indicate which button is being pressed

### CODE REVIEW

**Comment by GeneKao** [comment]
@Licini, I tried the mouse picking function, but it doesn't work on my laptop. 
The mouse position is shifted and may not be calculated correctly. I can only pick the object by clicking its bottom-right.

**Comment by Licini** [comment]
> 
> 
> @Licini, I tried the mouse picking function, but it doesn't work on my laptop.
> The mouse position is shifted and may not be calculated correctly. I can only pick the object by clicking its bottom-right.

Thanks for checking! I will be looking into this asap

**Comment by Licini** [comment]
> @Licini, I tried the mouse picking function, but it doesn't work on my laptop.
> The mouse position is shifted and may not be calculated correctly. I can only pick the object by clicking its bottom-right.

@GeneKao this should be fixed now, turned out retina screen doubles the resolution

**Comment by GeneKao** [comment]
@Licini thanks the mouse picking works now! 

One more small suggestion though. Since we are selecting using the left mouse button for clicking, I think it becomes pretty inconvenient when we have a lot of meshes on the screen; rotating camera conflicts with objects picking. I will suggest we could have the same usage as Rhino, right-click for camera rotating and shift + left-clicking to pan the view.

**Comment by Licini** [comment]
> @Licini thanks the mouse picking works now!
> 
> One more tiny suggestion though. Since we are selecting using the left mouse button for clicking, I think it becomes pretty inconvenient when we have a lot of meshes on the screen; rotating camera conflicts with objects picking. I will suggest we could have the same usage as Rhino, right-click for camera rotating and shift + left-clicking to pan the view.

@tomvanmele what would be your thoughts one changing mouse buttons?

**Comment by brgcode** [comment]
i agree that the mouse buttons functionality should be reviewed

**Comment by brgcode** [comment]
perhaps separate pull request?

**Comment by Licini** [comment]
> perhaps separate pull request?

yep sure, so left => select,   right => rotate,  right+shift => pan,  wheel => zoom ?

**Pull request merged**
